/*
  Parameter File: Hub VNet — Production
  ======================================
  Deployment target : rg-networking-prod (East US)
  VNet name         : vnet-hub-prod-eus  (auto-generated by naming convention)
  Purpose           : Central hub for hub-spoke topology. Hosts shared services,
                      Azure Firewall subnet, and VPN/ExpressRoute gateway subnet.

  Deploy:
    az deployment group create \
      --resource-group rg-networking-prod \
      --template-file ../main.bicep \
      --parameters @vnet-hub-prod.bicepparam
*/

using '../main.bicep'

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------
param environment  = 'prod'
param location     = 'eastus'
param workloadName = 'hub'

// ---------------------------------------------------------------------------
// Address Space
// ---------------------------------------------------------------------------
param addressPrefixes = [
  '10.0.0.0/16'
]

// ---------------------------------------------------------------------------
// Subnets
// ---------------------------------------------------------------------------
param subnets = [
  // Azure Firewall — fixed name required by Azure, must be /26 or larger
  {
    name          : 'AzureFirewallSubnet'
    addressPrefix : '10.0.0.0/26'
  }
  // VPN Gateway — fixed name required by Azure
  {
    name          : 'GatewaySubnet'
    addressPrefix : '10.0.1.0/27'
  }
  // Azure Bastion — fixed name required by Azure
  {
    name          : 'AzureBastionSubnet'
    addressPrefix : '10.0.2.0/26'
  }
  // Shared services (DNS, management VMs, etc.)
  {
    name          : 'snet-shared-services'
    addressPrefix : '10.0.4.0/24'
    networkSecurityGroupResourceId : ''   // attach an NSG resource ID here when available
    routeTableResourceId           : ''   // attach a UDR resource ID here when available
    serviceEndpoints               : []
    privateEndpointNetworkPolicies : 'Disabled'
  }
  // Private endpoints subnet
  {
    name          : 'snet-private-endpoints'
    addressPrefix : '10.0.5.0/24'
    privateEndpointNetworkPolicies : 'Disabled'
    privateLinkServiceNetworkPolicies : 'Disabled'
  }
]

// ---------------------------------------------------------------------------
// DNS
// ---------------------------------------------------------------------------
// Leave empty to use Azure-provided DNS, or specify custom servers:
// param dnsServers = ['10.0.4.4', '10.0.4.5']
param dnsServers = []

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------
// Replace with your Log Analytics Workspace resource ID
param logAnalyticsWorkspaceResourceId = '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-monitoring-prod/providers/Microsoft.OperationalInsights/workspaces/law-platform-prod'
param diagnosticRetentionDays         = 90

// ---------------------------------------------------------------------------
// Governance
// ---------------------------------------------------------------------------
param resourceLock = 'CanNotDelete'

// ---------------------------------------------------------------------------
// Mandatory Tags  (ALL fields are required by org policy)
// ---------------------------------------------------------------------------
param mandatoryTags = {
  CostCenter   : 'CC-NETWORKING-001'
  Owner        : 'platform-networking@contoso.com'
  BusinessUnit : 'Platform Engineering'
}

param additionalTags = {
  Criticality  : 'High'
  DataClass    : 'Internal'
}
